### ISSUE TITLE
Error running example - SystemJS not supported in browser

### ISSUE THREAD

**Issue by MumblesNZ** [typeorm/browser-example#6]
Hey,

Ran the example as per the README in Chrome - Version 64.0.3282.39 (Official Build) beta (64-bit). But get a console error as below. Any guidance is appreciated:

```
(index):24 Error: (SystemJS) This option/function is not supported in the browser environment. Failed operation: require("debug").
	Error: This option/function is not supported in the browser environment. Failed operation: require("debug").
	    at Function.PlatformTools.load (http://localhost:3000/node_modules/typeorm/typeorm-browser.js:1407:31)
	    at execute (http://localhost:3000/node_modules/typeorm/typeorm-browser.js:29602:52)
	Error loading http://localhost:3000/src/index.js
	    at Function.PlatformTools.load (http://localhost:3000/node_modules/typeorm/typeorm-browser.js:1407:31)
	    at execute (http://localhost:3000/node_modules/typeorm/typeorm-browser.js:29602:52)
	Error loading http://localhost:3000/src/index.js
```

**Comment by MumblesNZ** [comment]
Got the example to work by setting the following in package.json. It seems this example doesn't work with the latest typeorm build. 

 ```
 "dependencies": {
    "@types/node": "8.0.26",
    "reflect-metadata": "0.1.10",
    "systemjs": "0.19.47",
    "typeorm": "0.1.0"
  },
```

**Comment by daniel-lang** [comment]
You are right, take a look at typeorm/typeorm#1344, we broke browser support for version 0.1.8, but it should be working again with 0.1.9
